# Generated by Django 3.1.7 on 2021-04-04 00:38

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Palate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palate_name', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('email3', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('website', models.CharField(max_length=50)),
                ('tax_no', models.CharField(max_length=50)),
                ('kpp_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_corrno', models.CharField(max_length=50)),
                ('bank_bicno', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.region')),
            ],
        ),
    ]
