# Generated by Django 3.1.7 on 2021-04-04 05:10

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_palate_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.region')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=50)),
                ('event_type_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_login', models.CharField(max_length=20)),
                ('write_access', models.BooleanField()),
                ('administrator', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='palate',
            name='region',
        ),
        migrations.AlterField(
            model_name='palate',
            name='bank_account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='palate',
            name='bank_bicno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='palate',
            name='bank_corrno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='palate',
            name='kpp_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='palate',
            name='tax_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='palate',
            name='website',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('address_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('personal_data_date', models.DateField()),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('email3', models.EmailField(max_length=254)),
                ('registered_address', models.CharField(max_length=50)),
                ('post_address', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('mobile_phone', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('tax_no', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
                ('male_gender', models.BooleanField()),
                ('education_document_series', models.CharField(max_length=10)),
                ('education_document_number', models.CharField(max_length=10)),
                ('education_document_surname', models.CharField(max_length=20)),
                ('palate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.palate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.position')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('event_conditions', models.CharField(max_length=50)),
                ('event_comment', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request_deadline', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.IntegerField()),
                ('regular', models.BooleanField()),
                ('event_folder', models.FileField(max_length=254, upload_to=None)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.city')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.eventtype')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.manager')),
                ('palate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.palate')),
            ],
        ),
        migrations.AddField(
            model_name='palate',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.city'),
        ),
    ]
